import type { OcrData } from "./api/ocr";
import type { RecommendResponse } from "./api/recommend";
import type { SalesCustomer, Product } from "./api/customer";

export const mockOcrData: OcrData[] = [
  {
    id: "mock-receipt-1",
    receiptId: "REC-2023-001",
    receiptDate: "2023-10-25T14:30:00Z",
    createdAt: "2023-10-25T14:35:00Z",
    updatedAt: "2023-10-25T14:35:00Z",
    customerId: "CUST-001",
    dealerId: "DEALER-001",
    sourceImageKeys: ["mock-receipt-image"],
    dealer: {
      id: "DEALER-001",
      name: "Demo Dealer",
      address: "123 Demo Street",
      tels: ["02-123-4567"],
      taxId: "1234567890123",
      createdAt: "2023-01-01T00:00:00Z",
      updatedAt: "2023-01-01T00:00:00Z",
    },
    customer: {
      id: "CUST-001",
      name: "Demo Customer",
      address: "456 Demo Avenue",
      tels: ["081-234-5678"],
      taxId: "9876543210987",
      createdAt: "2023-01-01T00:00:00Z",
      updatedAt: "2023-01-01T00:00:00Z",
    },
    global_average_confidence: 0.98,
    summary: {
      subtotal: "1,000.00",
      subtotal_items: "2",
      subtotal_qty: "3",
      discount: "50.00",
      grand_total: "950.00",
      cash: "1,000.00",
      change: "50.00",
    },
    items: [
      {
        id: "item-1",
        name: "Demo Product A",
        createdAt: "2023-10-25T14:35:00Z",
        updatedAt: "2023-10-25T14:35:00Z",
        receiptId: "mock-receipt-1",
        piece: "2",
        price: 400.0,
        total: 800.0,
        type: "TARGET",
      },
      {
        id: "item-2",
        name: "Demo Product B",
        createdAt: "2023-10-25T14:35:00Z",
        updatedAt: "2023-10-25T14:35:00Z",
        receiptId: "mock-receipt-1",
        piece: "1",
        price: 200.0,
        total: 200.0,
        type: "other",
      },
    ],
  },
];

export const mockRecommendData = (customerHANA: string, saleTarget: string): RecommendResponse => ({
  customer: {
    id: customerHANA,
  },
  sale_target: Number(saleTarget),
  group: {
    group_id: 1,
    selected_products: [
      {
        customer: customerHANA,
        sales_district: "Mock District",
        product: "SKU-DEMO-001",
        material_brand: "BRAND-A",
        material_color: "Red",
        group_cat: "Board",
        _category: "best",
        category: "best",
        group_mat: "Board",
        channel: "Retail",
        total_qty_1y: 2000,
        price_per_unit: "280.00",
        weight_per_unit: "10",
        mock_stock: 1000,
        used_qty: 250,
        used_final_price: 70000,
        _score: 9.8,
        _cat: "Board",
        stock: 1000,
        price: 280,
        final_price: 70000,
        total_weight: 2500,
        reason: "Best seller, consistent monthly orders.",
      },
      {
        customer: customerHANA,
        sales_district: "Mock District",
        product: "SKU-DEMO-002",
        material_brand: "BRAND-A",
        material_color: "Brown",
        group_cat: "Wood",
        _category: "potential",
        category: "potential",
        group_mat: "Wood",
        channel: "Retail",
        total_qty_1y: 500,
        price_per_unit: "450.00",
        weight_per_unit: "15",
        mock_stock: 500,
        used_qty: 100,
        used_final_price: 45000,
        _score: 8.5,
        _cat: "Wood",
        stock: 500,
        price: 450,
        final_price: 45000,
        total_weight: 1500,
        reason: "Premium product with high profit margin.",
      },
    ],
    group_total_price: 115000,
    group_total_weight: 4000,
    truck: {
      single_truck_option: {
        truck_type: "6-Wheel Truck",
        truck_description: "6-Wheel Truck Option",
        trucks_needed: 1,
        max_weight: 5000,
        shipping_price: 1200,
        total_capacity: 5000,
      },
    },
    group_summary: "Mock Suggestion for Demo",
  },
});

export const mockCustomers: SalesCustomer[] = [
  {
    customerHANA: "1002023",
    name: "Demo Customer A",
    channel: "Retail",
    salesOffice: "BKK",
    salesGroup: "Group 1",
  },
  {
    customerHANA: "1000516",
    name: "Demo Customer B",
    channel: "Retail",
    salesOffice: "BKK",
    salesGroup: "Group 1",
  },
  {
    customerHANA: "1000022",
    name: "Demo Customer C",
    channel: "Retail",
    salesOffice: "BKK",
    salesGroup: "Group 2",
  },
  {
    customerHANA: "1000828",
    name: "Demo Customer D",
    channel: "Wholesale",
    salesOffice: "UPC",
    salesGroup: "Group 3",
  },
  {
    customerHANA: "1001673",
    name: "Demo Customer E",
    channel: "Retail",
    salesOffice: "BKK",
    salesGroup: "Group 2",
  },
];

export const mockProducts: Product[] = [
  { sku: "SKU-DEMO-001", name: "Demo Product 1", price: 100, groupCat: "Board", groupMat: "Board" },
  { sku: "SKU-DEMO-002", name: "Demo Product 2", price: 200, groupCat: "Wood", groupMat: "Wood" },
  { sku: "SKU-DEMO-003", name: "Demo Product 3", price: 300, groupCat: "Paint", groupMat: "Paint" },
  { sku: "SKU-DEMO-004", name: "Demo Product 4", price: 400, groupCat: "Ply", groupMat: "Ply" },
  { sku: "SKU-DEMO-005", name: "Demo Product 5", price: 500, groupCat: "Infill", groupMat: "Infill" },
];
